export const CHANGE_DIFFICULTY_PAGE = "change_difficulty";
export const GAME_PAGE = "game";
export const FINAL_PAGE = "final";
export const pathToCard = "./static/img";
export const cards = [
   "туз пики.png",
   "король пики.png",
   "валет пики.png",
   "дама пики.png",
   "10 пики.png",
   "9 пики.png",
   "8 пики.png",
   "7 пики.png",
   "6 пики.png",
   "туз черви.png",
   "король черви.png",
   "валет черви.png",
   "дама черви.png",
   "10 черви.png",
   "9 черви.png",
   "8 черви.png",
   "7 черви.png",
   "6 черви.png",
   "туз крести.png",
   "король крести.png",
   "валет крести.png",
   "дама крести.png",
   "10 крести.png",
   "9 крести.png",
   "8 крести.png",
   "7 крести.png",
   "6 крести.png",
   "туз бубны.png",
   "король бубны.png",
   "валет бубны.png",
   "дама бубны.png",
   "10 бубны.png",
   "9 бубны.png",
   "8 бубны.png",
   "7 бубны.png",
   "6 бубны.png",
];
